const { createClient } = window.supabase || {};
if (!createClient) { throw new Error('Supabase library failed to load. Please refresh the page.'); }
const supabase=createClient('https://wldgbdkzgzwgyteyofow.supabase.co','sb_publishable_RlYaofMqQE0QaVpepeUo5Q_Zms1TYN_',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'}});
let me=null,profiles=[],competitions=[],matches=[];const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function showTab(t){['dash','comp','matches','rankings','players','profile','admin'].forEach(x=>$(x)?.classList.toggle('hidden',x!==t));['Dash','Comp','Matches','Rankings','Players','Profile','Admin'].forEach(x=>$('tab'+x)?.classList.toggle('active',x.toLowerCase()===t));if(t==='profile')renderProfile();if(t==='admin')renderAdmin();if(t==='rankings')renderRankings();if(t==='players')renderPlayers()}window.showTab=showTab;window.scrollToCreate=()=>setTimeout(()=>$('createBox')?.scrollIntoView({behavior:'smooth'}),50);
function msg(t,ok=false){$('msg').textContent=t;$('msg').style.color=ok?'#9cff9c':''}function authErr(e){let m=String(e?.message||e||'');if(m.toLowerCase().includes('invalid login'))return'Email or password is incorrect.';if(m.toLowerCase().includes('anonymous'))return'Use email and password login.';return m||'Something went wrong.'}
async function signIn(){let email=$('email').value.trim().toLowerCase(),password=$('password').value;if(!email||!password)return msg('Enter email and password.');msg('Logging in…');try{let {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){let em=String(error.message||'').toLowerCase();$('resendBtn')?.classList.toggle('hidden',!em.includes('confirm'));return msg(authErr(error));}if(!data?.session){return msg('Login did not create a session. Check your email confirmation setting in Supabase.');}await load()}catch(e){msg(authErr(e))}}async function signUp(){let email=$('email').value.trim().toLowerCase(),password=$('password').value;if(!email||!password)return msg('Enter email and password.');if(password.length<8)return msg('Password must be at least 8 characters.');msg('Creating account…');let {data,error}=await supabase.auth.signUp({email,password,data:{display_name:email.split('@')[0]},options:{emailRedirectTo:`${location.origin}/`}});if(error)return msg(authErr(error));if(data.session)await load();else{$('resendBtn')?.classList.remove('hidden');msg('Account created. Check your email to confirm.',true)}}async function resendConfirmation(){let email=$('email').value.trim().toLowerCase();if(!email)return msg('Enter your email first.');let {error}=await supabase.auth.resend({type:'signup',email,options:{emailRedirectTo:`${location.origin}/`}});if(error)return msg(authErr(error));msg('Confirmation email sent again.',true)}async function forgotPassword(){let email=$('email').value.trim().toLowerCase();if(!email)return msg('Enter your email first.');let {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/reset.html`});if(error)return msg(authErr(error));msg('Password reset email sent.',true)}async function signOut(){await supabase.auth.signOut();location.reload()}
async function load(){try{let {data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;let user=session?.user;if(!user){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}let {data:p,error}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;if(!p){let ins=await supabase.from('profiles').upsert({id:user.id,display_name:user.user_metadata?.display_name||user.email?.split('@')[0]||'Player'},{onConflict:'id'}).select().single();if(ins.error)throw ins.error;p=ins.data}me=p;let ps=await supabase.from('profiles').select('*').order('display_name');profiles=ps.data||[];$('user').textContent=`${p.display_name} • ${p.role||'member'}`;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('tabAdmin').classList.toggle('hidden',p.role!=='admin');await renderAll()}catch(e){console.error(e);$('login').classList.remove('hidden');$('app').classList.add('hidden');msg(authErr(e))}}
async function createCompetition(){if(!me)return;let name=$('cname').value.trim();if(!name)return alert('Enter tournament name.');let format=$('format').value;let {data,error}=await supabase.rpc('create_competition',{p_name:name,p_type:'tournament',p_format:format,p_max_players:Number($('maxPlayers').value)||8,p_start_date:$('startDate').value||null,p_end_date:$('endDate').value||null});if(error)return alert('Could not create tournament: '+error.message);$('cname').value='';await renderAll();openCompetition(typeof data==='string'?data:data?.id)}
async function joinCompetition(id){
  if(!me)return;
  let {data:existing,error:checkErr}=await supabase.from('competition_members').select('user_id').eq('competition_id',id).eq('user_id',me.id).maybeSingle();
  if(checkErr)return alert('Could not check membership: '+checkErr.message);
  if(existing){await openCompetition(id);return}
  let {error}=await supabase.from('competition_members').insert({competition_id:id,user_id:me.id});
  if(error){
    if(String(error.message||'').toLowerCase().includes('duplicate key')){
      await openCompetition(id);
      return;
    }
    return alert(error.message);
  }
  await renderAll();
  openCompetition(id);
}
function pname(id){return profiles.find(p=>p.id===id)?.display_name||'Player'}
async function openCompetition(id){let c=competitions.find(x=>x.id===id);if(!c)return;let cm=await supabase.from('competition_members').select('user_id').eq('competition_id',id);let ids=(cm.data||[]).map(x=>x.user_id);let mm=await supabase.from('matches').select('*').eq('competition_id',id).order('match_date').order('start_time');let ms=mm.data||[];let mine=ids.includes(me.id),creator=c.creator_id===me.id||me.role==='admin';$('detail').classList.remove('hidden');$('detail').innerHTML=`<div class="comp"><div><h2>🏆 ${esc(c.name)}</h2><span class="pill">${esc(c.format)} • ${esc(c.status)}</span></div><div class="row">${!mine?`<button onclick="joinCompetition('${id}')">Join</button>`:''}${creator?`<button class="alt" onclick="generateFixtures('${id}')">Generate Fixtures</button>`:''}${creator?`<button class="alt" onclick="resetTournament('${id}')">Reset Tournament</button>`:''}${creator?`<button class="danger" onclick="deleteCompetition('${id}')">Delete Tournament</button>`:''}<button class="ghost" onclick="$('detail').classList.add('hidden')">Close</button></div></div><p class="muted">${ids.length}/${c.max_players} players • ${c.start_date||'No start date'} → ${c.end_date||'No end date'}</p><h3>Players</h3><div>${ids.map(x=>`<span class="pill" style="margin:3px">${esc(pname(x))}${creator?` <button class="danger" style="padding:2px 7px;margin-left:5px" onclick="removeMember('${id}','${x}')">Remove</button>`:''}</span>`).join(' ')}</div><h3 style="margin-top:20px">Fixtures</h3>${renderFixtures(ms)}<h3 style="margin-top:20px">${c.format==='knockout'?'Knockout Bracket':'Standings'}</h3>${c.format==='knockout'?renderBracket(ms):renderStandings(ids,ms)}`}
function renderFixtures(ms){return ms.length?ms.map(x=>`<div class="item"><div class="comp"><b>${esc(pname(x.home_player))} ${x.status==='completed'?`<strong>${x.home_score} - ${x.away_score}</strong>`:'vs'} ${esc(pname(x.away_player))}</b><span class="pill">${esc(x.status)}</span></div><div class="muted small">${esc(x.match_date||'')} ${esc(x.start_time||'')} ${x.round_no?`• Round ${x.round_no}`:''}</div></div>`).join(''):'<div class="note">No fixtures yet.</div>'}
function renderStandings(ids,ms){let r=ids.map(id=>({id,n:pname(id),mp:0,w:0,d:0,l:0,gf:0,ga:0,pts:0})),m=Object.fromEntries(r.map(x=>[x.id,x]));ms.filter(x=>x.status==='completed').forEach(x=>{let h=m[x.home_player],a=m[x.away_player];if(!h||!a)return;h.mp++;a.mp++;h.gf+=+x.home_score||0;h.ga+=+x.away_score||0;a.gf+=+x.away_score||0;a.ga+=+x.home_score||0;if(x.home_score>x.away_score){h.w++;h.pts+=3;a.l++}else if(x.home_score<x.away_score){a.w++;a.pts+=3;h.l++}else{h.d++;a.d++;h.pts++;a.pts++}});r.sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga));return `<div class="table-wrap"><table><tr><th>#</th><th>Player</th><th>MP</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>PTS</th></tr>${r.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.n)}</td><td>${x.mp}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td>${x.gf}</td><td>${x.ga}</td><td>${x.gf-x.ga}</td><td><b>${x.pts}</b></td></tr>`).join('')}</table></div>`}
function renderBracket(ms){let groups={};ms.forEach(x=>{let r=x.round_no||1;(groups[r]??=[]).push(x)});return `<div class="bracket">${Object.keys(groups).sort((a,b)=>a-b).map(r=>`<div class="round"><h3>Round ${r}</h3>${groups[r].map(x=>`<div class="match">${esc(pname(x.home_player))} <b>${x.status==='completed'?x.home_score:'-'}</b><br>${esc(pname(x.away_player))} <b>${x.status==='completed'?x.away_score:'-'}</b></div>`).join('')}</div>`).join('')}</div>`}
async function removeMember(competitionId,userId){
  let c=competitions.find(x=>x.id===competitionId);
  if(!c || (c.creator_id!==me.id && me.role!=='admin'))return alert('Only the tournament creator or an admin can remove members.');
  if(userId===c.creator_id)return alert('The tournament creator cannot be removed.');
  if(!confirm(`Remove ${pname(userId)} from this tournament?`))return;
  let {error}=await supabase.from('competition_members').delete().eq('competition_id',competitionId).eq('user_id',userId);
  if(error)return alert('Could not remove member: '+error.message);
  await renderAll();
  openCompetition(competitionId);
}
async function resetTournament(id){
  let c=competitions.find(x=>x.id===id);
  if(!c || (c.creator_id!==me.id && me.role!=='admin'))return alert('Only the tournament creator or an admin can reset it.');
  if(!confirm(`Reset "${c.name}"? This will delete all fixtures/results and set the tournament back to open.`))return;
  let {error:meErr}=await supabase.from('matches').delete().eq('competition_id',id);
  if(meErr)return alert('Could not delete fixtures/results: '+meErr.message);
  let {error:ceErr}=await supabase.from('competitions').update({status:'open'}).eq('id',id);
  if(ceErr)return alert('Fixtures were removed, but tournament status could not be reset: '+ceErr.message);
  await renderAll();
  openCompetition(id);
}
async function generateFixtures(id){let cm=await supabase.from('competition_members').select('user_id').eq('competition_id',id);let ids=(cm.data||[]).map(x=>x.user_id);if(ids.length<2)return alert('At least 2 players needed.');let existing=await supabase.from('matches').select('id').eq('competition_id',id);if(existing.data?.length)return alert('Fixtures already exist.');let pairs=[];let c=competitions.find(x=>x.id===id);if(c.format==='knockout'){let arr=[...ids].sort(()=>Math.random()-.5);for(let i=0;i+1<arr.length;i+=2)pairs.push({competition_id:id,home_player:arr[i],away_player:arr[i+1],match_date:new Date().toISOString().slice(0,10),start_time:'18:00',end_time:'19:00',status:'upcoming',round_no:1})}else{for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)pairs.push({competition_id:id,home_player:ids[i],away_player:ids[j],match_date:new Date().toISOString().slice(0,10),start_time:'18:00',end_time:'19:00',status:'upcoming',round_no:1})}if(!pairs.length)return alert('No fixtures could be generated. Make sure the tournament has at least 2 players.');let {error}=await supabase.from('matches').insert(pairs);if(error)return alert('Could not generate fixtures: '+error.message);let {error:upErr}=await supabase.from('competitions').update({status:'active'}).eq('id',id);if(upErr)return alert('Fixtures generated, but tournament status could not be updated: '+upErr.message);await renderAll();openCompetition(id)}
async function submitResult(){let id=$('matchSelect').value;if(!id)return alert('No match selected.');let hs=Number($('hs').value),as=Number($('as').value),file=$('resultShot').files?.[0];if(!Number.isInteger(hs)||!Number.isInteger(as)||hs<0||as<0)return alert('Enter valid scores.');if(!file)return alert('Upload the final-results screenshot.');if(file.size>6*1024*1024)return alert('Screenshot must be 6MB or smaller.');$('resultMsg').textContent='Uploading proof…';let path=`${me.id}/${id}-${Date.now()}.${(file.name.split('.').pop()||'jpg').toLowerCase()}`;let up=await supabase.storage.from('match-screenshots').upload(path,file,{upsert:false,contentType:file.type});if(up.error)return $('resultMsg').textContent='Upload failed: '+up.error.message;let url=supabase.storage.from('match-screenshots').getPublicUrl(path).data.publicUrl;let {error}=await supabase.from('matches').update({home_score:hs,away_score:as,status:'completed',submitted_by:me.id,submitted_at:new Date().toISOString(),screenshot_url:url}).eq('id',id);if(error)return $('resultMsg').textContent='Could not save result: '+error.message;$('resultMsg').textContent='Result submitted and standings updated.';await renderAll()}
function calcRanking(){
 let r=profiles.map(p=>({id:p.id,n:p.display_name||'Player',mp:0,w:0,d:0,l:0,gf:0,ga:0,pts:0})),m=Object.fromEntries(r.map(x=>[x.id,x]));
 matches.filter(x=>x.status==='completed').forEach(x=>{let h=m[x.home_player],a=m[x.away_player];if(!h||!a)return;h.mp++;a.mp++;h.gf+=+x.home_score||0;h.ga+=+x.away_score||0;a.gf+=+x.away_score||0;a.ga+=+x.home_score||0;if(+x.home_score>+x.away_score){h.w++;h.pts+=3;a.l++}else if(+x.home_score<+x.away_score){a.w++;a.pts+=3;h.l++}else{h.d++;a.d++;h.pts++;a.pts++}});
 return r.sort((a,b)=>b.pts-a.pts||(b.w-a.w)||(b.gf-b.ga));
}
function renderRankings(){let r=calcRanking();$('rankingTable').innerHTML='<div class="table-wrap"><table><tr><th>#</th><th>Player</th><th>MP</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>PTS</th></tr>'+r.map((x,i)=>'<tr><td class="'+(i<3?'rank1':'')+'">'+(i+1)+'</td><td><b>'+esc(x.n)+'</b></td><td>'+x.mp+'</td><td>'+x.w+'</td><td>'+x.d+'</td><td>'+x.l+'</td><td>'+(x.gf-x.ga)+'</td><td><b>'+x.pts+'</b></td></tr>').join('')+'</table></div>' || '<div class="muted">No players yet.</div>'}
function renderPlayers(){let r=calcRanking();$('playersGrid').innerHTML=r.map((x,i)=>'<div class="stat"><label>#'+(i+1)+' PLAYER</label><strong style="font-size:20px">'+esc(x.n)+'</strong><span>'+x.pts+' pts • '+x.w+' wins • '+x.mp+' matches</span></div>').join('') || '<div class="muted">No players yet.</div>'}
async function renderProfile(){let mine=matches.filter(x=>x.status==='completed'&&(x.home_player===me.id||x.away_player===me.id)),s={mp:mine.length,w:0,d:0,l:0,gf:0,ga:0,pts:0};mine.forEach(x=>{let home=x.home_player===me.id,gf=home?+x.home_score:+x.away_score,ga=home?+x.away_score:+x.home_score;s.gf+=gf;s.ga+=ga;if(gf>ga){s.w++;s.pts+=3}else if(gf===ga){s.d++;s.pts++}else s.l++});['MP','W','D','L','GF','GA','Pts'].forEach(k=>$("p"+k).textContent=s[k.toLowerCase()]??0);let ts=competitions.filter(c=>c.creator_id===me.id);$('pT').textContent=ts.length;$('history').innerHTML=ts.map(c=>`<div class="item"><b>${esc(c.name)}</b><div class="muted small">${esc(c.status)} • ${esc(c.format)}</div></div>`).join('')||'<div class="muted">No tournament history yet.</div>'}
async function renderAdmin(){$('adminList').innerHTML=competitions.map(c=>`<div class="item"><div class="comp"><div><b>${esc(c.name)}</b><div class="muted small">${esc(c.status)} • ${esc(c.format)}</div></div><button class="danger" onclick="closeTournament('${c.id}')">Mark completed</button></div></div>`).join('')||'<div class="muted">No tournaments.</div>'}async function closeTournament(id){let {error}=await supabase.from('competitions').update({status:'completed'}).eq('id',id);if(error)alert(error.message);else renderAll()}
async function deleteCompetition(id){
  let c=competitions.find(x=>x.id===id);
  if(!c)return;
  if(c.creator_id!==me.id && me.role!=='admin')return alert('Only the tournament creator or an admin can delete this tournament.');
  if(!confirm(`Delete "${c.name}"? This will also remove its members and fixtures.`))return;
  let {error}=await supabase.from('competitions').delete().eq('id',id);
  if(error)return alert('Could not delete tournament: '+error.message);
  $('detail')?.classList.add('hidden');
  await renderAll();
}
async function renderAll(){let cs=await supabase.from('competitions').select('*').order('created_at',{ascending:false});competitions=cs.data||[];let mm=await supabase.from('matches').select('*').order('match_date').order('start_time');if(mm.error){console.error('Matches load error:',mm.error);matches=[];}else matches=mm.data||[];let ps=await supabase.from('profiles').select('*').order('display_name');profiles=ps.data||[];$('compCount').textContent=competitions.length;$('upcoming').textContent=matches.filter(x=>String(x.status).toLowerCase()==='upcoming'&&(String(x.home_player)===String(me.id)||String(x.away_player)===String(me.id))).length;$('completed').textContent=matches.filter(x=>x.status==='completed').length;$('members').textContent=profiles.length;$('competitions').innerHTML=competitions.map(c=>`<div class="item"><div class="comp"><div><b>${esc(c.name)}</b><div class="muted small">${esc(c.format)} • ${esc(c.status)} • max ${c.max_players}</div></div><div class="row"><button class="ghost" onclick="openCompetition('${c.id}')">Open</button>${c.creator_id!==me.id?`<button class="alt" onclick="joinCompetition('${c.id}')">Join</button>`:''}${(c.creator_id===me.id||me.role==='admin')?`<button class="danger" onclick="deleteCompetition('${c.id}')">Delete</button>`:''}</div></div></div>`).join('')||'<div class="muted">No tournaments yet.</div>';$('myComps').innerHTML=competitions.filter(c=>c.creator_id===me.id).map(c=>`<div class="item"><b>${esc(c.name)}</b><div class="muted small">${esc(c.format)} • ${esc(c.status)}</div></div>`).join('')||'<div class="muted">You have not created a tournament yet.</div>';$('matchSelect').innerHTML=matches.filter(x=>String(x.status).toLowerCase()==='upcoming'&&(String(x.home_player)===String(me.id)||String(x.away_player)===String(me.id))).map(x=>`<option value="${x.id}">${esc(pname(x.home_player))} vs ${esc(pname(x.away_player))} — ${esc(x.match_date)}</option>`).join('')||'<option value="">No upcoming matches</option>';$('results').innerHTML=matches.filter(x=>x.status==='completed').slice(0,30).map(x=>`<div class="item">${esc(pname(x.home_player))} <b>${x.home_score}-${x.away_score}</b> ${esc(pname(x.away_player))}<div class="muted small">${esc(x.match_date||'')}</div></div>`).join('')||'<div class="muted">No results yet.</div>'}
window.signIn=signIn;window.signUp=signUp;window.resendConfirmation=resendConfirmation;window.forgotPassword=forgotPassword;window.signOut=signOut;window.createCompetition=createCompetition;window.joinCompetition=joinCompetition;window.openCompetition=openCompetition;window.generateFixtures=generateFixtures;window.removeMember=removeMember;window.resetTournament=resetTournament;window.submitResult=submitResult;window.closeTournament=closeTournament;window.deleteCompetition=deleteCompetition;supabase.auth.onAuthStateChange(()=>setTimeout(load,0));load();
